services:
  device_agent:
    image: spaneng/doover_device_agent:apps
    network_mode: host
    attach: false

  sample_wifi_rotate:
    build: ../
    network_mode: host
    restart: unless-stopped
    depends_on:
      device_agent:
        condition: service_healthy
    environment:
      - APP_KEY=test_app_key
      - CONFIG_FP=/app/simulators/app_config.json
